.pre-commit-config.yaml, docs/conf.py, docs/requirements.txt, pyproject.toml, setup.cfg, src/dcqc/__init__.py, src/dcqc/enums.py, src/dcqc/file.py, src/dcqc/filesystems/remote_file.py, src/dcqc/filesystems/synapsefs.py, src/dcqc/mixins.py, src/dcqc/parsers.py, src/dcqc/suites/suite_abc.py, src/dcqc/target.py, src/dcqc/tests/test_abc.py, src/dcqc/tests/tests.py, tests/test_file.py, tests/test_suites.py, tests/test_tests.py
This PR was something I started working on as a side-project, but I ended up building on top of these improvements for IBCDPE-448, so I'm including it here as a PR related to a subtask. Note that I originally intended on filling in docstrings for all submodules, but just doing it for the `file` submodule took a lot of time because I also made improvements to its API. My goal is to progressively fill in docstrings as I work on py-dcqc. 
Here's a summary of the changes introduced here:
- I documented the `file` submodule. 
- Most of the changes in `file.py` are documentation-related. 
- I noticed a few low-hanging fruits for improvements.
- New `interrogate` pre-commit hook.
- This will help maintain "docstring coverage" once we get that percentage up.
- Note that the minimum allowed is …
=> [IBCDPE-457] Improve and document `file` submodule

.pre-commit-config.yaml, Dockerfile, Pipfile, Pipfile.lock, setup.cfg, src/dcqc/file.py, src/dcqc/suites/suites.py, src/dcqc/tests/test_abc.py, src/dcqc/tests/tests.py, tests/data/example.jsonld, tests/data/files.csv, tox.ini
During today's Code Space meeting, I demonstrated how easy it is to implement new tests for new file types. Instead of throwing away that code, I'm opening a PR, which can act as documentation for now if anyone wants to contribute new tests and/or file types. 
Note that I started the `all` "package extra" to capture dependencies needed for running the tests. This way, the basic dependencies are kept minimal. 
```console
pip install dcqc[all]
```
Here's the relevant snippet from the acceptance test report: 
<details>
<summary>JsonLdSuite</summary>
```json
{
"type": "JsonLdSuite",
"target": {
"type": "Target",
"id": "0006",
"files": [
{
"url": "tests/data/example.jsonld",
"metadata": {
"md5_checksum": "56bb5f34da6d6df2ade3ac37e25586b7"
},
"type": "JSON-LD",
"local_path": …
```
=> Demonstrate implementation for new file types and tests

src/docker/build.sh
After adding the `TARBALL_PATH` build argument to the Dockerfile, I forgot to update the associated `build.sh` script to provide a value.
=> Fix docker build script

.github/workflows/ci.yml, setup.cfg, tests/conftest.py, tests/test_acceptance.py, tests/test_main.py, tests/test_tests.py, tox.ini
One of the major motivations for #13 is that the test suite would be much faster without the `SynapseFS` tests. This PR takes advantage of the fact that the tests are now relatively fast. For example, there's no need to limit which tests are run on different Python versions and operating systems. I'm now running all tests on all combinations in the `ci.yml` workflow. 
I also took the opportunity to clean up the pytest marks based on Tom's feedback a few PRs back. I now just have a `slow` mark, which is enforced by the `markers` section in `setup.cfg`. Currently, all of my tests take less than 0.03 seconds except for the large acceptance test (which interacts with Synapse) and a CLI test (which spawns two subprocesses). For now, both of these fall under my definition of slow because I like …
=> Speed up py-dcqc test suite

src/dcqc/file.py, src/dcqc/mixins.py, src/dcqc/tests/tests.py, tests/test_file.py
This change was prompted by work at closing the code coverage gap for the `file` submodule. I decided to drop the `get_local_path()` method in favor of a Python property like `name`. 
Since I wanted the local path to be included in the serialized `File` JSON output, I wanted to generalized what I had started with the `name` property. That's what motived the `_serialized_properties` class attribute. If you want a property to appear in the output JSON, you should list it in `_serialized_properties` and the `SerializableMixin` will handle the rest. This allowed me to remove the `File`-specific `to_dict()` implementation. 
The changes to the tests are mostly to use this new API (`file.local_path` instead of `file.get_local_path()`) as well as additional tests to close the test coverage gap. …
=> Revamp the way that local paths are handled by the `File` class

src/dcqc/main.py, src/dcqc/mixins.py, tests/conftest.py, tests/test_acceptance.py, tests/test_file.py, tests/test_main.py, tests/test_target.py
This PR continue my work at closing gaps in code coverage. This one tackles the `main`, `target`, and `mixins` submodules, which are now at 100% coverage. For transparency, the change in `create_targets()` was because the if statement wasn't going to be used by Nextflow, so I got rid of it for now in the spirit of YAGNI. Same with the removal of the `is_dataclass()` entry in the if-else block. 
**Edit:** I noticed that the acceptance test is at risk of failing due to concurrent tests trying to upload to the same file. I've used the approach I created for `SynapseFS` testing to create test run-specific folders on Synapse. Note that I'm using the `fs` package instead of `synapseclient` to remain agnostic of the backend. 
```
---------- coverage: platform darwin, python 3.11.1-final-0 …
```
=> Close code coverage gaps with `main`, `target`, and `mixins`

src/dcqc/mixins.py, src/dcqc/suites/suite_abc.py, src/dcqc/tests/test_abc.py, tests/conftest.py, tests/test_suites.py, tests/test_tests.py
Similar to #18, I'm working on closing any gaps in test coverage. This PR focuses on the gaps in the `tests` and `suites` submodules. You'll also notice that I created some pytest fixtures to reduce some repetition.
```
---------- coverage: platform darwin, python 3.11.1-final-0 ----------
Name                           Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------
src/dcqc/__init__.py               9      0      0      0   100%
src/dcqc/__main__.py               2      0      0      0   100%
src/dcqc/file.py                 160      0     54      0   100%
src/dcqc/main.py                  95      0     32      0   100%
src/dcqc/mixins.py                68      0     34      0   100%
src/dcqc/parsers.py …
```
=> Close code coverage for `suites` and `tests` submodules

Pipfile.lock, setup.cfg, src/dcqc/__main__.py, src/dcqc/file.py, src/dcqc/parsers.py, src/dcqc/reports.py, tests/data/file.json, tests/data/generate.py, tests/data/suite.json, tests/data/target.json, tests/data/test.computed.json, tests/data/test.external.json, tests/data/test.internal.json, tests/data/tests.json, tests/test_main.py, tests/test_parsers.py, tests/test_reports.py
Alright, here's the final PR to achieve 100% test coverage for `dcqc`. It's worth noting that this coverage doesn't rely on the slower tests (including the end-to-end acceptance test). So, 100% of the code base is tested in under 2 seconds. 🙌 
You'll notice that I tried using `pytest-xdist` to speed up the tests even more, but for now, it slows them down, presumably because of the overhead associated with parallelizing them. Once we have more tests, it'll make more sense to enable parallelized testing.
```
---------- coverage: platform darwin, python 3.11.1-final-0 ----------
Name                           Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------
src/dcqc/__init__.py               9      0      0      0   100% …
```
=> Close code coverage for `parsers` and `reports` submodules

src/dcqc/tests/tests.py
This is a short-term fix to the Docker Hub rate limits that we easily run into due to our current infrastructure.
=> Copy image to Quay.io to Docker Hub rate limits

src/dcqc/file.py, src/dcqc/suites/suites.py, tests/data/example.tsv, tests/data/files.csv, tests/data/staged_targets/example.tsv
This PR supports TSV file validation following the example in [#12](https://github.com/Sage-Bionetworks-Workflows/py-dcqc/pull/12). The `TSVSuite` class inherits the existing `Md5ChecksumTest` and `FileExtensionTest`. In `tests/data` I have added an `example.tsv` file and a line to `files.csv` with the URL, File Type, and MD5 Checksum for the example file. I tested my changes using the following commands in the CLI:
```
dcqc create-targets tests/data/files.csv targets
dcqc stage-target targets/target-0007.json tsv_target.json staged_targets
dcqc create-tests -rt Md5ChecksumTest,FileExtensionTest targets/target-0007.json test_files
dcqc compute-test test_files/target-0007.Md5ChecksumTest.json test_results/md5_result.json
dcqc compute-test test_files/target-0007.FileExtensionTest.json …
```
=> [ORCA-82] Support TSV files for `py-dcqc`

src/dcqc/main.py, tests/test_main.py
This PR introduces a simple command for performing QC on a single file. It skips all external tests for simplicity. This command is mainly intended for testing and demonstration purposes. In practice, we expect users to use `nf-dcqc`. 
```console
❯ dcqc qc-file -t TIFF -m '{"md5_checksum": "c7b08f6decb5e7572efbe6074926a843"}' ./tests/data/circuit.tif
{
"type": "TiffSuite",
"target": {
"type": "Target",
"id": null,
"files": [
{
"url": "tests/data/circuit.tif",
"metadata": {
"md5_checksum": "c7b08f6decb5e7572efbe6074926a843"
},
"type": "TIFF",
"name": "circuit.tif",
"local_path": "/var/folders/10/vcs16lfs07sddbfz881cvfb40000gq/T/dcqc-staged-k5pb2fnz/circuit.tif"
}
]
},
"suite_status": {
"required_tests": [
"FileExtensionTest",
"LibTiffInfoTest",
"Md5ChecksumTest"
],
"skipped_tests": [ …
```
=> [IBCDPE-558] Add `qc-file` CLI command for performing single-file QC

src/dcqc/tests/tests.py
Amends `GrepDateTest` to
- Negate the exit code such that a match returns exit 1 (test fails) and no match returns exit 0 (test passes)
- Removes `-w` option so that terms such as `<AcquisitionDate>` where the risk term is not a isolated word now match
- Adds `-a` option to explicitly treat binary files as text
- Adds `-q` option to suppress output as is not needed by the test
Note that for TIFF files this only searches within values of Tags where the content is a string, such as `ImageDescription`
We may wish to add an additional test that searches the `DateTime` tag itself.
=> Fix GrepDateTest

src/dcqc/tests/tests.py
Amends `GrepDateTest` to
- Negate the exit code such that a match returns exit 1 (test fails) and no match returns exit 0 (test passes)
- Removes `-w` option so that terms such as `<AcquisitionDate>` where the risk term is not a isolated word now match
- Adds `-a` option to explicitly treat binary files as text
- Adds `-q` option to suppress output as is not needed by the test
Note that for TIFF files this only searches within values of Tags where the content is a string, such as `ImageDescription`
We may wish to add an additional test that searches the `DateTime` tag itself.
=> Fix grep date test

CONTRIBUTING.md
This PR adds information to `CONTRIBUTING.md` that will help contributors to test and troubleshoot external tests.
=> [ORCA-230] Adds external test contribution info

src/dcqc/main.py, src/dcqc/mixins.py, src/dcqc/parsers.py, src/dcqc/suites/suite_abc.py, src/dcqc/target.py, src/dcqc/tests/base_test.py, src/dcqc/tests/bioformats_info_test.py, src/dcqc/tests/file_extension_test.py, src/dcqc/tests/grep_date_test.py, src/dcqc/tests/json_load_test.py, src/dcqc/tests/jsonld_load_test.py, src/dcqc/tests/libtiff_info_test.py, src/dcqc/tests/md5_checksum_test.py, src/dcqc/tests/ome_xml_schema_test.py, src/dcqc/tests/tiff_tag_306_date_time_test.py, tests/conftest.py, tests/data/generate.py, tests/data/suite.json, tests/data/target.json, tests/data/test.computed.json, tests/data/test.external.json, tests/data/test.internal.json, tests/data/tests.json, tests/test_parsers.py, tests/test_suites.py, tests/test_target.py, tests/test_tests.py
Ahead of implementing a multi-file QC test, I decided to refactor the `Target` class to be a base class with a common interface. I then added a `SingleTarget` subclass with methods/properties that only make sense for single-file targets. Tests can then decide whether to use the general `BaseTarget` interface or the additional methods in the `SingleTarget` interface. 
In this PR, I noticed that I was reusing the same pattern for `list_subclasses()` and `get_subclass_by_name()`, so I created another mixin class (`SubclassRegistryMixin`) to add that "registry" functionality to a base class. 
The number of files changed is high mostly because I renamed the `Target` class to `SingleTarget` to avoid confusion.
=> [ORCA-233] Refactor `Target` ahead of multi-file QC tests

src/dcqc/tests/bioformats_info_test.py, src/dcqc/tests/ome_xml_schema_test.py, tests/test_tests.py
This PR is a bug fix in response to @adamjtaylor reporting that the `BioFormatsTest` was not working.
Both the `BioFormatsTest` and `OmeXmlSchemaTest` were not updated along with the other external tests in #35. They were missed due to missing test coverage for their ability to evaluate exit codes.
Both tests are updated to evaluate exit codes the same way the other external tests do, and the missing test coverage is rectified in this PR.
=> [ORCA-236] Adds missing code handling and tests for external tests

src/dcqc/file.py, src/dcqc/tests/base_test.py, src/dcqc/tests/bioformats_info_test.py, src/dcqc/tests/grep_date_test.py, src/dcqc/tests/libtiff_info_test.py, src/dcqc/tests/ome_xml_schema_test.py, src/dcqc/tests/tiff_tag_306_date_time_test.py, tests/test_tests.py
This is a WIP.
This PR simplifies external tests, and enables the changes in the `nf-dcqc` PR linked below by removing the string manipulation function introduced in #35 and instead passing the name of the staged file wrapped in quotes, thereby emulating the path which Nextflow expects and would use in a command
It is paired with this [PR](https://github.com/Sage-Bionetworks-Workflows/nf-dcqc/pull/7) on `nf-dcqc`.
=> [ORCA-234] Improve file path handling

src/dcqc/file.py
This PR adds the `.svs` and `.scn` file extensions to the `TIFF` file type. These changes have been tested both with a `dcqc` run in the `test` configuration and with a `qc-file` command execution where I temporarily changed the `circuit.tif` file within the repository to have the `.svs` and `.scn` extensions (example output below).
```
dcqc qc-file -t TIFF -m '{"md5_checksum": "c7b08f6decb5e7572efbe6074926a843"}' ./tests/data/circuit.svs
{
"type": "TiffSuite",
"target": {
"id": null,
"files": [
{
"url": "tests/data/circuit.svs",
"metadata": {
"md5_checksum": "c7b08f6decb5e7572efbe6074926a843"
},
"type": "TIFF",
"name": "circuit.svs",
"local_path": "/var/folders/sr/3g4hnkfd4ld306tty7kqf1rr0000gr/T/dcqc-staged-_4mndfo1/circuit.svs"
}
],
"type": "SingleTarget"
},
"suite_status": { …
```
=> [ORCA-257] Adds `.svs` and `.scn` and extensions to `TIFF` file type

src/dcqc/suites/suites.py
This PR adds support for tests specific to `.txt` files by introducing the `TXTSuite`. This change has been tested with `nf-dcqc` both locally and on [Tower](https://tower-dev.sagebionetworks.org/orgs/Sage-Bionetworks/workspaces/example-dev-project/watch/j9JI6PCtNsRZH). Example output using the `qc-file` command:
```
dcqc qc-file -t TXT -m '{"md5_checksum": "14758f1afd44c09b7992073ccf00b43d"}' tests/data/test.txt
{
"type": "TXTSuite",
"target": {
"id": null,
"files": [
{
"url": "tests/data/test.txt",
"metadata": {
"md5_checksum": "14758f1afd44c09b7992073ccf00b43d"
},
"type": "TXT",
"name": "test.txt",
"local_path": "/var/folders/sr/3g4hnkfd4ld306tty7kqf1rr0000gr/T/dcqc-staged-23i95246/test.txt"
}
],
"type": "SingleTarget"
},
"suite_status": {
"required_tests": [
"Md5ChecksumTest", …
```
=> [ORCA-262] Adds TXTSuite

src/dcqc/file.py, src/dcqc/suites/suites.py
This PR adds support for tests specific to `.csv` files by introducing the `CSVSuite`. This change has been tested with `nf-dcqc` both locally and on [Tower](https://tower-dev.sagebionetworks.org/orgs/Sage-Bionetworks/workspaces/example-dev-project/watch/j9JI6PCtNsRZH). Example output using the qc-file command:
```
dcqc qc-file -t CSV -m '{"md5_checksum": "ab49a084ccdd0c04879fbbc3ba6b00e8"}' tests/data/small.csv
{
"type": "CSVSuite",
"target": {
"id": null,
"files": [
{
"url": "tests/data/small.csv",
"metadata": {
"md5_checksum": "ab49a084ccdd0c04879fbbc3ba6b00e8"
},
"type": "CSV",
"name": "small.csv",
"local_path": "/var/folders/sr/3g4hnkfd4ld306tty7kqf1rr0000gr/T/dcqc-staged-z5bxrknl/small.csv"
}
],
"type": "SingleTarget"
},
"suite_status": {
"required_tests": [
"Md5ChecksumTest", …
```
=> [ORCA-263] Adds CSVSuite

setup.cfg
Problem:
URLs are not linking back to the DCQC github - they're linking out to pyscaffold
Solution:
Update URLs to this GH project
=> Correcting the links in the setup.cfg

tests/conftest.py, tests/test_external_tests.py, tests/test_internal_tests.py
**Problem:**
Unit tests for `py-dcqc` Internal and External tests are disorganized, making it more difficult than it needs to be to contribute new DCQC tests.
**Solution:**
Organize all unit tests that specifically evaluate the functionality of DCQC Internal and External tests into test classes to make it clear what unit tests belong together. It should now be simpler for contributors to add new DCQC tests and any needed unit tests.
=> [ORCA-289] Refactor External and Internal Testing Unit Tests as Test Classes

.github/workflows/ci.yml, .readthedocs.yml, Pipfile.lock, setup.cfg, tests/conftest.py, tests/test_external_tests.py, tests/test_file.py, tests/test_internal_tests.py, tests/test_reports.py, tests/test_suites.py, tests/test_target.py, tox.ini
**Problem:**
The test file, target, and suite objects defined in `conftest.py` that we use in our unit tests have confusing names, making it difficult to know what is happening in our tests.
**Solution:**
Change the names to a loose convention of `good_<type_of_file>` for "good" files and `<reason_why_this_file_is_bad_<type_of_file>` for "bad" files.
Notes:
- All tests run and pass as expected after these changes.
- I also went ahead and made a couple of changes to simplify some of the logic in `conftest.py`.
=> [ORCA-288] Test Object Naming Refactor

src/dcqc/file.py
[QPTIFF](https://docs.openmicroscopy.org/bio-formats/5.9.2/formats/perkinelmer-vectra-qptiff.html) is a TIFF-based image format used by PerkinsElmer Vecra mIF and Akoya Phenocycler CODEX instruments. This PR adds basic support for them by including files with the `.qptiff` extension in the TIFF file type.
=> Add support for QPTIFF

.github/workflows/ci.yml, Pipfile.lock, setup.cfg, src/dcqc/tests/grep_date_test.py, tox.ini
**Problem:**
There appears to have been a breaking [change](https://github.com/docker/docker-py/issues/3256) for `docker-py` introduced by `requests` v2.32.0. This change should prevent that from breaking our CI and development environments.
**Solution:**
Pin the `requests` version to <=2.31.
**Notes:**
- I also added `gh_token` as an argument to the keepalive-workflow in the CI workflow. See this [PR](https://github.com/Sage-Bionetworks/fs-synapse/pull/4) for the reasoning.
- There was also an additional [issue](https://github.com/Sage-Bionetworks-Workflows/py-dcqc/actions/runs/9568869840/job/26380120004) with the container version being used (deprecation) in the `GrepDateTimeTest`, I bumped it up to the latest published version in `biocontainers`.
=> Pin `requests` version
